backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: "travel-packages"
    preview: false
    label: "Travel Packages"
    folder: "content/travel-packages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Location Title", name: "title", widget: "string" }
      - { label: "Travel Dates", name: "travel-dates", widget: "string" }
      - { label: "Featured Image", name: "featured-image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "testimonials"
    preview: false
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Give Random Title", name: "title", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "image", name: "image", widget: "image" }
